
name: AlpineBuild


on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.ini'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**test-alpine.yaml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          arch: armv7
          branch: edge
          extra-repositories: |
            http://dl-cdn.alpinelinux.org/alpine/edge/testing
          packages: >
            build-base
            libgit2-dev
            meson
            git 
            gcc 
            musl-dev 
            file-dev
            argp-standalone 
            g++ 
            linux-headers 
            klibc-dev 
            libxkbcommon-dev 
            libinput-dev 
            libx11-dev
            platformio-core 
            platformio-core-pyc 
            py3-meshtastic
            py3-pip
    
      - name: Print environment
        run: |
          gcc --version
          cat /etc/alpine-release
          cat /etc/apk/repositories
        shell: alpine.sh --root {0}

      - name: Build pio project
        run: |
          pio run
        shell: alpine.sh {0}


        
